author: Dream
author_url: https://dream-swp.com
github_url: https://github.com/swp-song/DSLocation
root_url: https://github.com/swp-song/DSLocation
module: DSLocation
output: docs
# documentation: Docs/*.md
# theme: fullwidth
# theme: jony
theme: apple
min-acl: public
# SMP
xcodebuild_arguments: ["-project", "Example/Example.xcodeproj", "-scheme", "Example"]

# jazzy 